# 비동기/동기 처리
### 동기 처리란?
- 동기 처리는 특정 코드의 연산이 끝나야, 즉 요청 후 응답을 받아야 그 다음의 코드 연산을 실행시키는 처리 방식이다
### 그렇다면 비동기 처리는?
- 비동기 처리는 동기 처리와 달리 특정 코드가 끝나지 않아도 다음 코드를 실행시키는 것이다. 한꺼번에 실행 된다고 생각하자. 

콜백 함수를 사용 하다보면, 콜백 함수를 너무 많이 사용하게 되어, 콜백 헬이 일어나게 된다.

# Promise?
이러한 콜백 헬을 막기 위해 ES6에서 Promise를 도입했다. 
- Promise는 인자로 비동기가 성공했을때의 콜백 함수와 실패 했을때의 콜백 함수를 받는다. 이것을 resolve와 reject라고 한다
**(여기서 쓰는 resolve와 reject의 명칭은 마음대로 해도 상관이 없다.)**

  ```jsx
  // Promise 객체의 생성
  const promise = new Promise((resolve, reject) => {
    // 비동기 작업을 수행한다.

    if (/* 비동기 작업 수행 성공 */) {
      resolve('result');
    }
    else { /* 비동기 작업 수행 실패 */
      reject('failure reason');
    }
  });

  ```

  ### Promise의 상태 정보
  - pending : 비동기 처리가 수행되지 않은 상태를 말한다.
  - fulfilled : 비동기 처리가 수행된 상태를 말한다.(성공)
  - rejected : 비동기 처리가 실패된 상태를 말한다.
  - settled : Promise의 상태가 pending이 아닌 상태를 말한다.
  ---

  ### Promise의 호출은?
  - 비동기 처리에 성공 했다면, 인자로 준 resolve 함수를 실행하고 실패했다면, reject 함수를 실행한다.
  - 이때 함수의 결과는 후속 처리 메소드로 보내지는데 이 후속 처리 메소드에는 **then**과 **catch**가 있다.
  ---
  ### then?
  then 메소드는 두 개의 인자를 콜백 함수로 전달 받는다. 첫번째 인자는 Promise가 성공적으로 실행 했을때 실행되고, 두번째 인자는 실패 했을때 실행된다. 여기서 두번째 인자는 선택적임으로 써도 되고 안 써도 된다, 하지만 안 쓸 경우 catch 메소드로 실패 했을때를 처리해 주어야 한다.
  ```jsx
    const myPromise = new Promise((resolve, reject) => {
    // 비동기 작업 수행
    resolve('성공!'); // resolve의 값으로 '성공!' 을 전달 한다.
  });

  myPromise.then((result) => {
    console.log(result); // '성공!'이 출력됩니다.
  });

  ```


  ```jsx
  fetch('https://api.example.com/data')
  .then(response => response.json())
  .then(data => {
    console.log(data);
    return data.length;
  })
  .then(length => {
    console.log(`Data length: ${length}`);
  })
  .catch(error => {
    console.error('Error:', error);
  });
  ```


  ### catch??
  catch는 Promise나 then에서 오류가 발생할 시, 실행된다.
  만약 then에 두번째 인자로 Promise가 실패 했을시에 대한 경우에 사용하는 콜백 함수를 넣어뒀다면, catch를 사용하지 않아도 된다. 하지만 사용하는 편이 좀 더 깔끔하기 때문에. 쓰는것이 좋다.
 
  ---
  ### Promise 체이닝
  then이나 catch로 promise를 연결하여 사용 할 수 있다. 이것으로 기존 콜백 함수의 문제인 콜백 헬을 해결 할 수 있다.

  ### 콜백 헬이 뭔데?
  콜백 헬이란 비동기 처리를 위해 콜백 함수를 계속하여 불러오면서, 들여쓰기가 많아져 가독성이 불편해지고 오류 수정이 어려워 지는 현상을 말한다.
  ```jsx
  function increase(number,callback){
  setTimeout(() =>{
     const result =  number+10;
        if(callback){
            callback(result);
        }
    },1000);
  }
  increase(1,result=>{
      console.log(result);
  })
  // 아래는 콜백지옥...
  console.log("작업시작");
  increase(0,result=>{
      console.log(result);
      increase(result,result=>{
          console.log(result);
          increase(result,result=>{
              console.log(result);
              increase(result,result=>{
                  console.log(result);
                  increase(result,result=>{
                      console.log(result);
                      increase(result,result=>{
                          console.log(result);
                          increase(result,result=>{
                              console.log(result);
                              console.log('작업완료');
                          })
                      })
                  })
              })
          })
      })
  })
  ```
  보다시피 보기 정말 불편하다. 


  ### Promise 체이닝으로 돌아와서,,

  ```jsx
    // 포스트 id가 1인 포스트를 검색하고 프로미스를 반환한다.
  promiseAjax('GET', `${url}/1`)
    // 포스트 id가 1인 포스트를 작성한 사용자의 아이디로 작성된 모든 포스트를 검색하고 프로미스를 반환한다.
    .then(res => promiseAjax('GET', `${url}?userId=${JSON.parse(res).userId}`))
    .then(JSON.parse)
    .then(render)
    .catch(console.error);
  ```

  이 코드처럼 결과를 전달하며, 여러 개의 프로미스를 연결 할 수 있다.

  # Async / Await  
  async와 await는 비동기 처리 패턴 중 가장 최근에 나온 문법이다. 복잡했던 promise를 조금 더 편하게 쓸 수 있으며, 읽기 좋은 코드 즉 가독성이 좋은 코드를 작성하게 도와준다.
  ### await의 기본 문법
    ```jsx
    async function 함수명() {
      await 비동기_처리_메서드_명();
    }
    ```
  ### async?
  async 키워드는 function 앞에 쓴다. function 앞에 async를 쓰면, 그 함수는 항상 프로미스를 반환한다. 프로미스가 아닌 값을 반환하더라도, 이행 상태의 프로미스 (resolved promise)를 반환한다.

  - 예제 코드 (1이 이행 프로미스로 반환된다.)
  ```jsx
  async function f() {
    return 1;
  }

  f().then(alert); // 1
  ```
  - 1을 Promise.resolved로 감싸도 같은 결과가 나온다.
  ```jsx
  async function f() {
    return Promise.resolve(1);
  }

  f().then(alert); // 1
  ```
  ### await??
  await는 async 함수 안에서 사용한다.
  await는 프로미스가 끝날때까지, 기다리는 역할을 한다.
  ```jsx
  async function f() {

    let promise = new Promise((resolve, reject) => {
      setTimeout(() => resolve("완료!"), 1000)
    });

    let result = await promise; // 프라미스가 이행될 때까지 기다림 (*)

    alert(result); // "완료!"
  }

  f();
  ```
  - ( * )로 표기된 줄이 중단 되었다가, 프로미스가 처리되면 실행이 재개된다.
  -  따라서 1초뒤에 "완료!"가 출력 된다.
  
  await는 프로미스가 처리될 때까지 함수 실행을 기다리게 만들기 때문에, 프로미스가 처리되면 그 결과와 함께 실행이 재개된다. 프로미스가 처리되길 기다리는 동안에는 엔진이 다른 일을 할 수 있기 때문에 cpu가 낭비 되지 않는다.

  ### async / await 에러 제어
  await에서 에러가 발생하면 await는 그 에러를 throw한다 그 에러는 try..catch를 사용하여 잡을 수 있다.
  ```jsx
  async function f() {

    try {
      let response = await fetch('http://유효하지-않은-주소');
    } catch(err) {
      alert(err); // TypeError: failed to fetch
    }
  }

  f();
  ```

  ### 별 의미 없는 내용
  - await를 왜 쓰는지 궁금해서 찾아보니, promise가 실행되어 값을 얻어야 다음 코드를 쓸 수 있는 경우도 있고, 해당 promise에서 오류가 발생했을시, 그 것을 고쳐야 하는 경우도 있기 때문에 await를 쓰는 것 같다.